### PR TITLE
[need to redo] Add GitHub Actions CI builds

### LINKED ISSUE #180: Add support for macOS on Travis CI
### Feature Description:

To render our tests more sensitive to other platform (see e.g. https://github.com/shimming-toolbox/shimming-toolbox/pull/179), we should extend our CI to other platforms. 

The low hanging fruit is to add support to macOs since it is available in Travis.

### PR DESCRIPTION
**Pull request by jidicula**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer

## Description

**Why this change was necessary**
Travis doesn't offer great support for macOS and is also beginning to
charge for macOS build minutes.

**What this change does**
 - Factors the Travis CI build config into a shell script
 - Calls that shell script in a GitHub Actions Workflow
 - Adds a matrix build in the GH Actions Workflow for macOS 10.15
 Catalina and 11.0 Big Sur (on Apple Silicon), Windows Server 2019,
 and Ubuntu 18, 20, and 16
 - Adds a matrix build in the GH Actions Workflow for Python 3.7 and
 3.8
 - Adds a build status badge to the README

**Additional context/notes/links**
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

## Linked issues

Resolves #180

### CODE REVIEW

**Comment by jidicula** [comment]
~Unfortunately it doesn't seem like there's an easy way to test GH Actions correctness until it's merged into `master` so I won't remove the Travis build config yet...~ jk I forgot to put it in a `workflows/` dir

**Review by jcohenadad — APPROVED** [review]
you rock! 🤘

**Comment by jidicula** [comment]
@jcohenadad 🤦‍♂️ I didn't put the YAML in a `workflows/` directory - should I revert or just make a hotfix PR?

**Comment by jcohenadad** [comment]
hotfix is fine 👍

**Pull request merged**
