### PR TITLE
Fix Travis coveralls post-build step

### LINKED ISSUE #143: coveralls crashing in Travis – pip package install needs to be corrected
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [x] I've described my environment
- [x] I've described the bug
- [x] I've described the steps to reproduce the behaviour
- [ ] I've included screenshots
- [x] I've given this issue the correct labels

### Environment details

Travis build

### Bug Description

```
441 $ coveralls
463 Traceback (most recent call last):
464  File "/home/travis/virtualenv/python3.7.6/bin/coveralls", line 8, in <module>
465    sys.exit(wear())
466  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/__init__.py", line 78, in wear
467    from coveralls.control import coveralls
468  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/control.py", line 2, in <module>
469    from coveralls.report import CoverallsReporter
470  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/report.py", line 6, in <module>
471    from coverage.report import Reporter
472  ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coverage/report.py)
```
See also https://travis-ci.com/github/shimming-toolbox/shimming-toolbox/builds/189211908#L463

### Reproduction Steps

Run a Travis build that passes.

### Potential Reasons behind Bug:

Seems to be a known issue (z4r/python-coveralls#74) that's fixed by using `pip install coveralls` instead.

### PR DESCRIPTION
**Pull request by jidicula**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer

## Description

**Why this change was necessary**
The `coveralls` post-success build step was erroring out due to the
now-wrong package being pip-installed.

**What this change does**
Modifies the setup step to install the correct coveralls package.

**Any side-effects?**
None noticed yet... Will update after running the build.
## Linked issues

Resolves #143 - coveralls crashing in Travis - pip package install needs to be corrected

### CODE REVIEW

**Comment by jidicula** [comment]
Seems to still be failing...
```
after_success
4210.77s$ coveralls
461Submitting coverage to coveralls.io...
462Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
463Traceback (most recent call last):
464  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/api.py", line 206, in wear
465    response.raise_for_status()
466  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
467    raise HTTPError(http_error_msg, response=self)
468requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
469
470During handling of the above exception, another exception occurred:
471
472Traceback (most recent call last):
473  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/cli.py", line 85, in main
474    result = coverallz.wear()
475  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/coveralls/api.py", line 209, in wear
476    raise CoverallsException('Could not submit coverage: {}'.format(e))
477coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

See https://travis-ci.com/github/shimming-toolbox/shimming-toolbox/builds/189213061#L461

**Comment by jidicula** [comment]
@kousu is this repo configured for coveralls and do we still need to include it in the build?

Could this possibly be related to the repo name change?

**Comment by po09i** [comment]
> Could this possibly be related to the repo name change?

The coverage report error was there before the repo name change. (I looked at the previous travis builds). 
Just noticed it's not the same error though so the name change could still related.

**Comment by jidicula** [comment]
🤔 interesting... I've requested Coveralls access for this repo – maybe that's why it was failing

**Comment by jidicula** [comment]
```
2.06s$ coveralls
740Submitting coverage to coveralls.io...
741Coverage submitted!
742Job #496.1
743https://coveralls.io/jobs/69076504
```
looks good!

**Review by po09i — APPROVED** [review]
Current status says unknown, I looked at the link and I'm assuming it will be activated once on master. If that's the case LGTM.

**Comment by jidicula** [comment]
> Current status says unknown, I looked at the link and I'm assuming it will be activated once on master

Yep, that's the case. We'll be sure once it's merged 🤞

**Pull request merged**
