### PR TITLE
Switch to using mambaforge

### PR DESCRIPTION
**Pull request by kousu**
This is mamba -- a faster version of conda -- plus conda-forge -- a more rapidly maintained package repository.

## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [ ] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer

## Linked issues

This is the same patch as https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/36.

### CODE REVIEW

**Comment by kousu** [comment]
And CI is failing. I don't know why CI is failing. I'll deal with it later.

**Comment by po09i** [comment]
As mentioned in https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/36, I am getting an error from scipy when using mamba to install shimming toolbox. This needs to be explored further but removing the need for scipy 1.6.0 fixed the issue. 

Scipy 1.6.0 was updated (79db4fc7af47803ce183d65944935b8ae4d6b133) from 1.5.0 (5f8e455ecca5371c56b69b1fd7af902da8b63bdc) to support missing features. 1.5.0 was the first version used in Shimming Toolbox. We had no need for further versions until now.

**Comment by po09i** [comment]
The CI seems to be failing to a similar MPL error encountered when debugging the fsleyes mamba PR: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/36#issuecomment-1239718367

**Comment by po09i** [comment]
CI was failing due to a warning in the sphinx build when importing `make_axes_locatable` from matplotlib when I updated to version 3.5. Version 3.3.4 is the latest version that does not throw this error.

**Comment by mathieuboudreau** [comment]
@kousu when I install mamba, I get this warning:

>Warning: Mamba support is still experimental and can result in differently solved environments!

How sure are we about the stability of this service?

**Review by po09i — APPROVED** [review]

**Pull request merged**
