### PR TITLE
Update API and CLI documentation

### LINKED ISSUE #222: Consider changing "_" for separating 2 words CLI options
### Description
We should decide how to call CLI options that have more than one word. We have been separating the words with "_". We could also chose "-".

For now we have been using "-mask_static" and "-remove_tmp". We could consider using "-mask-static" and "-remove-tmp".

### LINKED ISSUE #267: Add SCT to installation documentation
## Summary
We currently support SCT masking but we should include it in the documentation

### LINKED ISSUE #272: Complete the API refs in the documentation
In the doc, the CLI and API ref seems incomplete:
image

We should update that

### PR DESCRIPTION
**Pull request by po09i**
## Description
This PR
* adds the missing API and CLI functions to the documentation. Some of the docstring was adjusted to follow the sphinx guidelines to build the doc (#272, #267)
* changes the overall sections of the APIs and CLIs
* updates the remaining CLI still using the old single dash("-") convention to double dashes ("--") for consistency (#222)
  * updates the examples and tests accordingly
* updates the cli optinons using the old "_" seperating words to "-" (#222)

## Linked issues
Fixes #272 
Fixes #267
Fixes #222

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
LGTM!

**Comment by KevinBerard** [comment]
Everything seems good except the `st_realtime_zshim -h` no longer work.


Screenshot from 2021-06-04 14-42-11

**Comment by po09i** [comment]
We changed the CLI from `st_realtime_zshim` to `st_realtime_shim` since it outputs x, y and z coefficients now. It should work with the new name.

**Comment by KevinBerard** [comment]
The new command doesn't seem to be there. Do I need to reinstall Shimming-toolbox with this branch files to get the command?

On a side note, the [CLI](https://shimming-toolbox-py--277.org.readthedocs.build/en/277/cli_reference/cli.html#) doesn't have the -h option listed, is it normal?

Screenshot from 2021-06-07 10-50-21

**Comment by po09i** [comment]
> The new command doesn't seem to be there. Do I need to reinstall Shimming-toolbox with this branch files to get the command?

I believe you have to run `pip install -e .` in the branch yes.

> On a side note, the CLI doesn't have the -h option listed, is it normal?

Yes, the `sphinx-click` package does not show the `--help` option. I did not see a way to change this behaviour in their [doc](https://sphinx-click.readthedocs.io/en/latest/usage/). Either way I don't think we want to make a feature request since we are already showing the doc...

**Comment by KevinBerard** [comment]
> I believe you have to run `pip install -e .` in the branch yes.

Yes, with `pip install -e "../shimming-toolbox"` the new command get setup and everything works just fine. May we consider to mention this somewhere before merging?

**Review by KevinBerard — APPROVED** [review]
LGTM

**Comment by po09i** [comment]
> > I believe you have to run `pip install -e .` in the branch yes.
> 
> Yes, with `pip install -e "../shimming-toolbox"` the new command get setup and everything works just fine. May we consider to mention this somewhere before merging?

This was done in PR #270. I don't think I would mention it anywhere else.

**Pull request merged**
