### PR TITLE
Create numerical model data for multi-echo field maps

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves #1 

Completed conversion of the code & tests from the MATLAB implementation to Python.

Left to-do
* [x] Document & cleanup the code
* [x] Write up a demo in a Jupyter Notebook & add a Binder button.

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Finished cleaning up, ready for review.

I also wrote a notebook and setup the environment so that it can be run on MyBinder: [Binder](https://mybinder.org/v2/gh/shimming-toolbox/notebooks/mb/sim?filepath=simulate%2FNumericalModel_demo.ipynb)

I created the repo [shimming-toolbox/notebooks](https://github.com/shimming-toolbox/notebooks) to host notebooks for the project. My demo notebook in that repo is in [this branch](https://github.com/shimming-toolbox/notebooks/tree/mb/sim), which I'll open a PR for once this current PR is merged (because I'll need to change the branch from mb/sim to master when in the badge and postBuild)

**Comment by mathieuboudreau** [comment]
Also - someone with admin rights might want to change the default merge option to "squash" for this repo, or at least select it when merging this PR.

**Comment by jcohenadad** [comment]
> Also - someone with admin rights might want to change the default merge option to "squash" for this repo, or at least select it when merging this PR.

according to [this post](https://stackoverflow.com/questions/49203040/is-there-a-way-to-specify-a-default-option-for-merging-a-pull-request-in-github) the default option is the latest one-- we could disable the two other choices, but i would leave them (in case useful at some point).

**Comment by mathieuboudreau** [comment]
@kousu how do I merge changes from master, now that you rebase and merge at each pull request? The two branches have diverged, and the command-line instructions recommended by github above result in just an error and no guidance on how to resolve this:

>CONFLICT (modify/delete): requirements.txt deleted in a317a3b07d692c4044e5048e432435eba372ee0e and modified in HEAD. Version HEAD of requirements.txt left in tree.
Automatic merge failed; fix conflicts and then commit the result.

I've never dealt with rebase and merge in projects, only squash and merges, and for that one it was very easy to update branches.

**Comment by mathieuboudreau** [comment]
I tried to resolve the merge conflict with master that can't be resolved with GitHub's conflict web editor due to this repo's rebase option being turned on ("Linear History") using the advice in #4, but failed to do so cleanly (or in a way that I felt confident about it, since I always tried to avoid rewriting git histories in the past).

I'll leave it up to whoever reviews and merges this PR to deal with resolving this conflict cleanly - I just wrote up the code in this PR on my free time since I'm the one who wrote the code for it during the hackathon, but I don't have much time to actually dedicate to this anymore. The code is here and is documented if you want to integrate it to the project someday =)

**Comment by jcohenadad** [comment]
thank you @mathieuboudreau for your contribution, and sorry to hear about these conflicts (i know this is frustrating). We will take care of it.

**Comment by kousu** [comment]
> @kousu how do I merge changes from master when there are conflicts, now that you rebase and merge at each pull request? The two branches have diverged, and the command-line instructions recommended by github above result in just an error and no guidance on how to resolve this

It's almost identical to what you used, @mathieuboudreau :

```
git checkout master
git pull
git checkout feature-branch
git rebase master
# fix merge conflicts
git push --force
```

Anyway, sorry about the snag and thanks for offering the code. I've fixed up the merge conflicts (if you want to see what that looks like, it's [here](https://github.com/shimming-toolbox/shimming-toolbox-py/issues/14#issuecomment-657112309) and I'm going to take a look at this now.

**Review by jcohenadad — APPROVED** [review]
thanks a lot for your contirbution @mathieuboudreau !!!

**Pull request merged**
