### PR TITLE
Moved testing and docs packages in default installation

### LINKED ISSUE #96: Installation issue with zsh
the following command does not run on zsh
````
pip install -e .[testing]
zsh: no matches found: .[testing]
````

@lcbMGH will fill up with more info

### PR DESCRIPTION
**Pull request by ghost**
Minor change shifting testing packages to required installation, instead of extra, to add to ease of installation.

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
should the doc also be updated? (ie: remove the "[testing]" with pip command)

**Comment by lcbMGH** [comment]
What's the process for updating the docs? That feels like a good call, how can I do it?

**Comment by jcohenadad** [comment]
> @jcohenadad What's the process for updating the docs? That feels like a good call, how can I do it?

just remove the [testing] [here](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/docs/source/2_getting_started/1_installation.rst).

**Comment by lcbMGH** [comment]
> > @jcohenadad What's the process for updating the docs? That feels like a good call, how can I do it?
> 
> just remove the [testing] [here](https://github.com/shimming-toolbox/shimming-toolbox-py/blob/master/docs/source/2_getting_started/1_installation.rst).
> 
> EDIT 2020-09-21 12:53:12: actually, you might also want to do the same for [docs].
Should the instructions still include docs instructions? What's the use and decision around that being the only thing in the extras tab currently?

**Comment by jcohenadad** [comment]
> Should the instructions still include docs instructions? What's the use and decision around that being the only thing in the extras tab currently?

sorry i'm not sure i understand the question. Are you referring to the pip install command? (ie: if it should still include "docs")?

**Comment by lcbMGH** [comment]
> > Should the instructions still include docs instructions? What's the use and decision around that being the only thing in the extras tab currently?
> 
> sorry i'm not sure i understand the question. Are you referring to the pip install command? (ie: if it should still include "docs")?

Yes, and particularly why docs is in the extras section and not the required installation section. If we feel that it's simpler to move testing into the required install section so we don't have to worry about zsh bracket escape, why are we keeping docs there?

**Comment by jcohenadad** [comment]
> Yes, and particularly why docs is in the extras section and not the required installation section. If we feel that it's simpler to move testing into the required install section so we don't have to worry about zsh bracket escape, why are we keeping docs there?

I agree with you, hence my comment in https://github.com/shimming-toolbox/shimming-toolbox-py/pull/97#issuecomment-696239312: "you might also want to do the same for [docs]." (ie: put it in the default install pckgs), sorry if i was unclear.

**Comment by lcbMGH** [comment]
> > Yes, and particularly why docs is in the extras section and not the required installation section. If we feel that it's simpler to move testing into the required install section so we don't have to worry about zsh bracket escape, why are we keeping docs there?
> 
> I agree with you, hence my comment in [#97 (comment)](https://github.com/shimming-toolbox/shimming-toolbox-py/pull/97#issuecomment-696239312): "you might also want to do the same for [docs]." (ie: put it in the default install pckgs), sorry if i was unclear.

Phenomenal, I think I just misread. Thanks for the clarification!

**Comment by jcohenadad** [comment]
@gaspardcereza just told me he had trouble running pytest because not all packages were properly installed, so this is a +1 for doing this change (@gaspardcereza pls let us know if the error was coming from something else)

**Review by jcohenadad — APPROVED** [review]

**Comment by gaspardcereza** [comment]
> @gaspardcereza just told me he had trouble running pytest because not all packages were properly installed, so this is a +1 for doing this change (@gaspardcereza pls let us know if the error was coming from something else)

Yes I just tried it with this branch and it worked ! So I agree that it would be useful to merge it.

**Review by jcohenadad — APPROVED** [review]

**Review by po09i — CHANGES_REQUESTED** [review]
I'm not sure this is necessary, as discussed in the https://github.com/shimming-toolbox/shimming-toolbox-py/issues/96#issuecomment-696394639.

**Comment by po09i** [comment]
Added the `docs` back in the optional set up as discussed here https://github.com/shimming-toolbox/shimming-toolbox-py/issues/96#issuecomment-696863526

**Review by po09i — APPROVED** [review]

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
