### PR TITLE
Add documentation stub for dicom_to_nifti.py

### LINKED ISSUE #165: Add documentation stub for dicom_to_nifti.py
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Document the use of config/dcm2bids.json*)
- [x] I've described the enhancement for an existing feature
- [x] (optional) I've added some ideas about how to implement my suggestion
- [x] I've given this issue the correct labels

### Description of Problem / Inefficiency:

`dicom_to_nifti.py` wasn't added to the `api.rst` document, but should be in there in the `misc` section.
### Implementation Suggestion:

Write the stub following https://github.com/shimming-toolbox/shimming-toolbox/blame/master/docs/source/6_api_reference/api.rst#L51
### Additional Context / Screenshots:

None.

### PR DESCRIPTION
**Pull request by jidicula**
----

## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer

## Description

**Why this change was necessary**
`dicom_to_nifti.py` wasn't added to the `api.rst` document, but should
be in there in the `misc` section.

**What this change does**
See title.

**Any side-effects?**
Re-compile docs locally to see it update locally.

## Linked issues

Resolves #165

### CODE REVIEW

**Comment by po09i** [comment]
I'm wondering if CLIs should get there own sections in the documentation since they are not really APIs.. The `dicom_to_nifti` CLI is just a wrapper to the `dicom_to_nifti` API, which is where most of the documentation of the function should be.

**Comment by jidicula** [comment]
Well that was embarrassing, I was pushing commits to the wrong branch 🤦‍♂️.

Force-push incoming, I hope no one has pulled those 3 commits from yesterday locally 😬

**Comment by po09i** [comment]
I had, but thanks for the heads up I'll do the necessary fixes

**Comment by jidicula** [comment]
> I'm wondering if CLIs should get there own sections in the documentation since they are not really APIs.. The `dicom_to_nifti` CLI is just a wrapper to the `dicom_to_nifti` API, which is where most of the documentation of the function should be.

Yeah that's a good point. I have another PR coming soon for the environment checking that's entirely part of the CLI module, and I've put those docstubs in the API `misc` section too... Might be better to cut a new ticket just for the documentation refactor so this PR and #176 can be merged in faster.

**Review by po09i — APPROVED** [review]
I'll approve, I opened an issue #177 regarding my previous https://github.com/shimming-toolbox/shimming-toolbox/pull/166#issuecomment-724207032

**Pull request merged**
