### PR TITLE
Remove the need for sudo in the installer

### PR DESCRIPTION
**Pull request by kousu**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [ ] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer

## Description

The install script shouldn't demand root privileges. One of the big reasons for using conda is to make it easy to install dependencies without root; but even if this wasn't using conda it's very possible to package it without root.

## Linked issues

* https://github.com/neuropoly/computers/issues/201#issue-1004356523

### CODE REVIEW

**Comment by po09i** [comment]
We needed to use sudo in the CI when installing with the script, I'll remove that dependency now so we can test the install in the CI as well

**Comment by kousu** [comment]
In SCT we just assume that `curl` is so basic it's probably already there, and error out if it's not:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/b745313dcf5a342de9eda4393d3c102195704993/install_sct#L180

If the CI machine doesn't have it installed, instead of _removing_ it you could _move_ it from the install script to directly in the CI script, as an extra step, like

```
      - name: Package installation
        run: |
          echo "shimming-toolbox installation"
          sudo apt install -y curl

      - name: Package installation
        run: |
          echo "shimming-toolbox installation"
          make install
```

**Comment by kousu** [comment]
I haven't yet found a way to 100% bootstrap from nothing. You either need to:

- manually install Ubuntu
- manually install Windows
- manually install curl
- manually install docker
- manually install chocolatey
- etc etc

in order to get something going. It's just a matter of choosing where the line is for your project and tbh I think this is a reasonable split.

**Comment by po09i** [comment]
I think this is reasonable as well. I tested it on Joplin and it works! Thanks @kousu !

**Comment by kousu** [comment]
I added a note to the Linux install instructions about `curl`. I guess we're assuming Macs come with curl pre-installed always so I left that part alone?

**Review by po09i — APPROVED** [review]
LGTM!

**Pull request merged**
