### PR TITLE
Raise warning when loading RF nifti with missing SliceTiming

### LINKED ISSUE #251: Missing "SliceTiming" tag in B1 .json file
### Checklist

- [x] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [x] I've described my environment
- [x] I've described the bug
- [x] I've described the steps to reproduce the behaviour
- [ ] I've included screenshots
- [x] I've given this issue the correct labels

### Environment details

- [x] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)
- I used [dcm2niix](https://github.com/rordenlab/dcm2niix) version 20201224

Project version: Current master branch (30/03/2021) 

Operating System and version: MacOS Catalina

Python version: 3.8.5

Path to Python binary: /path/to/bin/python /Users/gaspard/miniconda3/venvs/shim_venv/bin/python

### Bug Description
When trying to convert a small RF mapping dataset (48 dicoms --> Phase and Magnitude for 8 coils over 3 slices), the created .json file does not have the "SliceTiming" tag.
With larger datasets that I tested (256 to 800 dicoms), this tag is created during the conversion.
This tag is useful for me because I use it in [load_nifit.py](https://github.com/shimming-toolbox/shimming-toolbox/blob/eb2b513a521c9b2ad8793e8fdf58511156df0277/shimmingtoolbox/load_nifti.py#L216) to ensure that the number of slices matches the 3rd dimension of the B1 array.

### Reproduction Steps
Run `st_dicom_to_nifti` on the data from the 26/03/2021 available on duke (\\duke.neuro.polymtl.ca\MRI\mni-7t).

### Potential Reasons behind Bug:
Might be due to a missing tag in the dicoms (couldn't identify it yet). Or maybe a bug in `dcm2niix`.

### Additional Context:
These pages gather list of tags that might be used to generate the "SliceTiming" tag in the json file:
- https://github.com/rordenlab/dcm2niix/tree/master/Siemens#slice-timing
- https://github.com/neurolabusc/dcm_qa_stc#siemens

### PR DESCRIPTION
**Pull request by gaspardcereza**
## Description
If missing SliceTiming tag in .json, only inform the user instead of raising an error.
I also refactored some tests to me clearer.

## Linked issues
Resolves #251

### CODE REVIEW

**Comment by gaspardcereza** [comment]
@po09i That's what we discussed earlier. I also cleaned some tests.

**Review by po09i — COMMENTED** [review]
It looks like raising a UserWarning interrupts the program which I don't think is the intention. I think `import warning` is what you are looking for.

**Comment by gaspardcereza** [comment]
> It looks like raising a UserWarning interrupts the program which I don't think is the intention. I think `import warning` is what you are looking for.

Great catch thank you ! It should work fine now.

**Review by po09i — APPROVED** [review]
Looks good!

**Pull request merged**
