### PR TITLE
ci: Add pre-commit configs

### LINKED ISSUE #199: Limit file size on commit
Problem: we would like to forbid commits that include files bigger than XX MB.
Possible implementations: 

- https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit/39578014#39578014
- https://gist.github.com/kiwidamien/a6a909ee196be8795b30431079074d64

Crossref: https://github.com/neuropoly/spinalcordtoolbox/issues/3100 https://github.com/neuropoly/axondeepseg/issues/423 https://github.com/ivadomed/ivadomed/issues/583

### PR DESCRIPTION
**Pull request by jidicula**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied the relevant labels to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer

## Description

**Why this change was necessary**
We want to enforce file size limits on commits to ensure contributors
don't accidentally commit massive files to the repo and pollute the
history. This should be checked both locally and on GitHub.

**What this change does**
 - Adds `pre-commit` as an optional `dev` dependency
 - Adds `pre-commit` hooks for YAML check, merge conflict string
 check, AST check, and large file (>500kb) check
 - Adds GitHub Action to run above pre-commit checks on each PR and
 push to master
 - Updates documentation to instruct contributors to install `dev` dependencies

**Additional context/notes/links**
 - https://github.com/pre-commit/pre-commit-hooks#check-added-large-files
 - https://pre-commit.com

## Linked issues

Resolves #199

### CODE REVIEW

**Comment by po09i** [comment]
Are the local hooks always run when we locally commit something or we need to manually run pre-commit to check?

**Comment by jidicula** [comment]
Once the project has been reinstalled with `pip install -e ".[docs,dev]"` and you've run `pre-commit install` once, the hooks will run automatically when you locally commit something.

**Review by po09i — APPROVED** [review]
Awesome, I'm scared to test it but if you have then it LGTM!

**Comment by jidicula** [comment]
@shimming-toolbox/editors once this PR is closed, please run `pip install -e ".[docs,dev]"`, then run `pre-commit install`.

**Comment by joshuacwnewton** [comment]
Cross-referencing the related issues on sister projects to get that sweet, sweet GH auto-linking UI magic:

* https://github.com/neuropoly/spinalcordtoolbox/issues/2705, https://github.com/neuropoly/spinalcordtoolbox/issues/3100
* https://github.com/ivadomed/ivadomed/issues/583
* https://github.com/neuropoly/data-management/issues/43

**Comment by vasudev-sharma** [comment]
Inspired by this PR, we're implementing the same feature in another sister project (**AxonDeepSeg**) see [here](https://github.com/neuropoly/axondeepseg/pull/464). 

The **pre-commit** hook in this PR requires the developer/contributor to do the mandatory step `pre-commit install ` so that the checks are being caught locally.

There might be instances where the developer might forget this step and this would lead to the checks being skipped locally.

In order to avoid this, for this, in the PR https://github.com/neuropoly/axondeepseg/pull/464, we are thinking to do add `pre-commit install` in the build script (**setup.py**) as a [post-install ](https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools/36902139#36902139)step via `setuptools`. 

I wish to know did you consider this option for installing pre-commit hooks? 

1. If yes, may I know why you didn't plan on keeping it?

2. If no, then may I know your thoughts on this?

**Comment by jidicula** [comment]
> I wish to know did you consider this option for installing pre-commit hooks?
> 
> 1. If yes, may I know why you didn't plan on keeping it?
> 2. If no, then may I know your thoughts on this?

I actually didn't know this was an option! It looks like it's viable, with the only caveat that it creates a bit of dependence on setup.py magic. Just remember to attempt triggering it only if the `dev` extra is the build option. My other worry about setup.py dependence is that it makes shifting to the recommended pyproject.toml dependency specification a bit harder - hopefully PSF comes up with something that replicates that functionality.

**Comment by vasudev-sharma** [comment]
Thanks @jidicula for your valuable inputs.

**Pull request merged**
